contacts/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from contacts.decorators import user_has_permission
from . import views


app_name = 'contacts'
urlpatterns = [
    url(r'^contact/?$', login_required(views.ContactsListView.as_view()), name='contact_list'),
    url(r'^(?P<contact_id>[0-9]+)/?$', login_required(user_has_permission(views.ContactDetailView.as_view())), name='contact_detail'),
    url(r'^add_contact/?$', login_required(views.AddContactView.as_view()), name='add_contact'),
    url(r'^add_address/?$', login_required(views.AddContactAddressView.as_view()), name='add_address'),
    url(r'^update_contact/(?P<contact_id>[0-9]+)/?$', login_required(user_has_permission(views.UpdateContactView.as_view())), name='update_contact'),
    url(r'^update_contact_address/(?P<address_id>[0-9]+)/?$',
        login_required(user_has_permission(views.UpdateContactAddressView.as_view())), name='update_contact_address'
        ),
    url(r'^delete/(?P<contact_id>\d+)/?$', login_required(user_has_permission(views.DeleteContactView.as_view())), name='delete_contact')
]

phone_directory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from phone_directory import settings

urlpatterns = [
    url(r'^contacts/', include('contacts.urls')),
    url(r'^', include('user_sessions.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
    ]

user_sessions/urls.py
from django.conf.urls import url

from . import views


app_name = 'user_sessions'
urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'^login/?$', views.LoginView.as_view(), name='login'),
    url(r'^logout/?$', views.LogoutView.as_view(), name='logout'),
    url(r'^register_user/?$', views.AddUserView.as_view(), name='register_user')
]

phone_directory/templates/phone_directory/form.html
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
</form>

phone_directory/templates/phone_directory/home.html
{% extends "phone_directory/layout.html" %}

{% block content %}

<b> Welcome to Phone Directory App !!!</b>
<p><a href="{% url 'user_sessions:login' %}">Click to go to Login Page</a></p>
<p><a href="{% url 'user_sessions:register_user' %}">Click here to Register</a></p>

{% endblock %}

phone_directory/templates/phone_directory/layout.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}"/>
    <title>Phone Directory App</title>
</head>

<body>

<header><H1 align="middle">My Phone Directory </H1></header>

{% if user.is_authenticated %}
    <h2 align="middle"> User: {{ user }} </h2>
    <h4 align="right"><a href="{% url 'user_sessions:logout' %}">logout</a></h4>

{% endif %}

{% block content %}
{% endblock %}

<footer><h3 align="middle">Some Footer Here !!!!!!!!!!!!!!!!!!!!!!!!!!!</h3></footer>

</body>
</html>