contacts/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from contacts.decorators import user_has_permission
from . import views


app_name = 'contacts'
urlpatterns = [
    url(r'^contact/?$', login_required(views.ContactsListView.as_view()), name='contact_list'),
    url(r'^(?P<contact_id>[0-9]+)/?$', login_required(user_has_permission(views.ContactDetailView.as_view())), name='contact_detail'),
    url(r'^add_contact/?$', login_required(views.AddContactView.as_view()), name='add_contact'),
    url(r'^add_address/?$', login_required(views.AddContactAddressView.as_view()), name='add_address'),
    url(r'^update_contact/(?P<contact_id>[0-9]+)/?$', login_required(user_has_permission(views.UpdateContactView.as_view())), name='update_contact'),
    url(r'^update_contact_address/(?P<address_id>[0-9]+)/?$',
        login_required(user_has_permission(views.UpdateContactAddressView.as_view())), name='update_contact_address'
        ),
    url(r'^delete/(?P<contact_id>\d+)/?$', login_required(user_has_permission(views.DeleteContactView.as_view())), name='delete_contact')
]

phone_directory/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

from phone_directory import settings

urlpatterns = [
    url(r'^contacts/', include('contacts.urls')),
    url(r'^', include('user_sessions.urls')),
    url(r'^admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT})
    ]

user_sessions/urls.py
from django.conf.urls import url

from . import views


app_name = 'user_sessions'
urlpatterns = [
    url(r'^$', views.HomePageView.as_view(), name='home'),
    url(r'^login/?$', views.LoginView.as_view(), name='login'),
    url(r'^logout/?$', views.LogoutView.as_view(), name='logout'),
    url(r'^register_user/?$', views.AddUserView.as_view(), name='register_user')
]

contacts/models.py
from django.db import models
from django.core.validators import RegexValidator
from django.contrib.auth.models import User


class Contact(models.Model):
    phone_regex = RegexValidator(
            regex=r'^\+?1?\d{9,20}$',
            message="Phone number must be entered in the format: '+999999999'. Up to 20 digits allowed."
    )

    user = models.ForeignKey(User)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=30)
    phone_number = models.CharField(validators=[phone_regex], max_length=20, blank=True)
    contact_image = models.ImageField(upload_to='contacts_images', default='contacts_images/default.png')

    def __str__(self):
        return self.name


class Address(models.Model):
    HOME = 'home'
    OFFICE = 'office'

    ADDRESS_CHOICES = (
        (HOME, 'Home Address'),
        (OFFICE, 'Office Address'),
    )

    contact = models.ForeignKey(Contact)
    address_selection = models.CharField(max_length=6, choices=ADDRESS_CHOICES, default=HOME)
    address_line = models.CharField(max_length=50)
    city = models.CharField(max_length=15)
    state = models.CharField(max_length=15)
    zip_code = models.CharField(max_length=15)
    country = models.CharField(max_length=20)

    def __str__(self):
        return self.country

contacts/forms.py
from django import forms

from contacts.models import Contact, Address


class NewContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'phone_number', 'contact_image']


class NewAddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = ['contact', 'address_selection', 'address_line', 'city', 'state', 'zip_code', 'country']

contacts/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse
from django.views import generic, View

from contacts.forms import NewContactForm, NewAddressForm
from .models import Contact, Address


class ContactsListView(View):
    template_name = "contacts/contact_list.html"

    def get(self, request):
        specific = Contact.objects.filter(user=request.user)
        return render(request, self.template_name, {'user_specific_contacts': specific})


class ContactDetailView(generic.DetailView):
    model = Contact
    pk_url_kwarg = 'contact_id'


class AddContactView(View):
    form_class = NewContactForm
    template_name = 'contacts/contact_form.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            contact = form.save(commit=False)
            contact.user = request.user
            contact.save()
            return HttpResponseRedirect(reverse('contacts:contact_list'))
        return render(request, self.template_name, {'form': form})


"""This one works too"""
# def add_contact_view(request):
#     if request.method == 'POST':
#         form = NewContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#         return HttpResponseRedirect(reverse('contacts:contact'))
#     else:
#         form = NewContactForm()
#         return render(request, 'contacts/contact_form.html', {'form': form})

"""This one works too"""
# class AddContactView(generic.CreateView):
#     model = Contact
#     fields = ['name', 'email', 'phone_number']
#     success_url = reverse_lazy('contacts:contact')


class AddContactAddressView(View):
    form_class = NewAddressForm
    template_name = 'contacts/address_form.html'

    def get(self, request):
        form = self.form_class()
        form.fields.get('contact').queryset=Contact.objects.filter(user=request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.save()
            return HttpResponseRedirect(reverse('contacts:contact_list'))
        return render(request, self.template_name, {'form': form})


class UpdateContactView(generic.UpdateView):
    model = Contact
    fields = ['name', 'email', 'phone_number', 'contact_image']

    pk_url_kwarg = 'contact_id'

    def get_success_url(self):
        return reverse('contacts:contact_detail', kwargs={'contact_id': self.get_object().id})


class UpdateContactAddressView(generic.UpdateView):
    model = Address
    fields = ['address_selection', 'address_line', 'city', 'state', 'zip_code', 'country']

    pk_url_kwarg = 'address_id'

    def get_success_url(self):
        return reverse('contacts:contact_detail', kwargs={'contact_id': self.get_object().contact.id})


class DeleteContactView(View):
    template_name = "contacts/delete_contact.html"

    def get(self, request, contact_id):
        return render(request, self.template_name, {'object': Contact.objects.get(id=contact_id)})

    def post(self, contact_id):
        contact = Contact.objects.get(id=contact_id)
        contact.delete()
        return HttpResponseRedirect(reverse('contacts:contact_list'))

contacts/templates/contacts/address_form.html
{% extends "phone_directory/layout.html" %}

{% block content %}
    <h3>Add/Edit Address</h3>
    {% include 'phone_directory/form.html' with form=form %}
{% endblock %}

contacts/templates/contacts/contact_detail.html
{% extends "phone_directory/layout.html" %}

{% block content %}
    <p><a href="{% url 'contacts:contact_list' %}">Back to Contact List</a></p>
    <p><a href="{% url 'contacts:update_contact' object.id %}">Update Contact</a></p>
    <h3>{{ object.name }}</h3>
    <p><b>Email: </b>{{ object.email }}</p>
    <p><b>Phone: </b>{{ object.phone_number }}</p>
    <p><b>Image: </b><img src="{{ object.contact_image.url }}" height="100"></p>

    {% for address in object.address_set.all %}
        <p><b><i>Address {{ address.address_selection }}:</i></b>
            {{ address.address_line }}, {{ address.city }},
            {{ address.state }}, {{ address.zip_code }}</p>
        <p><b>Country: </b>{{ address.country }}</p>
        <p><a href="{% url 'contacts:update_contact_address' address.id %}">
            Update Contact's {{ address.address_selection }} Address</a></p>
    {% endfor %}

    <p><a href="{% url "contacts:delete_contact" object.id %}">Delete</a></p>
{% endblock %}

contacts/templates/contacts/contact_form.html
{% extends "phone_directory/layout.html" %}


{% block content %}
    <h3>Add/Edit Contact</h3>
    {% include 'phone_directory/form.html' with form=form %}
{% endblock %}

contacts/templates/contacts/contact_list.html
{% extends "phone_directory/layout.html" %}

{% block content %}
<h3>My Contacts</h3>

    <p><a href="{% url 'contacts:add_contact' %}">Add Contact</a></p>
    <p><a href="{% url 'contacts:add_address' %}">Add Address Against a Contact</a></p>
    <br>
    {% for contact in user_specific_contacts %}
        <li><a href="{% url 'contacts:contact_detail' contact.id %}">{{ contact }}</a></li>
    {% endfor %}

{% endblock %}

contacts/templates/contacts/delete_contact.html
{% extends "phone_directory/layout.html" %}

{% block content %}
<form method="post">
    {% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
    <a href="{% url "contacts:contact_detail" contact_id=object.id %}">Cancel</a>
</form>
{% endblock %}

contacts/templates/contacts/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Home</title>
</head>
<header>

    <H1 align="middle">My Phone Directory </H1>
</header>

<body>
<b> Welcome to Phone Directory App !!!</b>
<p><a href="{% url 'contacts:login' %}">Click to go to Login Page</a></p>
</body>

<p><h3 align="middle"><footer>Some Footer Here !!!!!!!!!!!!!!!!!!!!!!!!!!!</footer></h3></p>
</html>

contacts/templates/contacts/layout.html
{% load staticfiles %}

<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{% static 'contacts/style.css' %}"/>
</head>
<header>

    <H1 align="middle">My Phone Directory </H1>

{% if user.is_authenticated %}
    <h2 align="middle"> User: {{ user }} </h2>

    <h4 align="right"> <a href="{% url 'contacts:logout' %}">logout</a></h4>
</header>

    {% block content %}
    {% endblock %}

{% else %}
    <a href="{% url 'contacts:login' %}">login</a>

{% endif %}


<p><h3 align="middle"><footer>Some Footer Here !!!!!!!!!!!!!!!!!!!!!!!!!!!</footer></h3></p>

contacts/templates/contacts/login.html
<h1>Login</h1>
{% block content %}
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% include 'contacts/form.html' with form=form %}

{% endblock %}